[project]
name = 'asim-project'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.divide-zero]
path = 'contracts/divide-zero.clar'
clarity_version = 2
epoch = 2.5

[contracts.function-stack-depth]
path = 'contracts/function-stack-depth.clar'
clarity_version = 2
epoch = 2.5

[contracts.shift-left]
path = 'contracts/shift-left.clar'
clarity_version = 2
epoch = 2.5

[contracts.shift-right]
path = 'contracts/shift-right.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
